//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectServiceClient.DiffFilesInterfaceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DiffFilesInterfaceRef.IDiffFilesInterface")]
    public interface IDiffFilesInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiffFilesInterface/compareFileLetterByLetter", ReplyAction="http://tempuri.org/IDiffFilesInterface/compareFileLetterByLetterResponse")]
        int compareFileLetterByLetter(string firstFileName, string secondFileName, int pattern);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiffFilesInterface/compareFileLetterByLetter", ReplyAction="http://tempuri.org/IDiffFilesInterface/compareFileLetterByLetterResponse")]
        System.Threading.Tasks.Task<int> compareFileLetterByLetterAsync(string firstFileName, string secondFileName, int pattern);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiffFilesInterface/percentCalculate", ReplyAction="http://tempuri.org/IDiffFilesInterface/percentCalculateResponse")]
        double percentCalculate(double distanceLevenhstein, double firstTextLenght);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiffFilesInterface/percentCalculate", ReplyAction="http://tempuri.org/IDiffFilesInterface/percentCalculateResponse")]
        System.Threading.Tasks.Task<double> percentCalculateAsync(double distanceLevenhstein, double firstTextLenght);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDiffFilesInterfaceChannel : ProjectServiceClient.DiffFilesInterfaceRef.IDiffFilesInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiffFilesInterfaceClient : System.ServiceModel.ClientBase<ProjectServiceClient.DiffFilesInterfaceRef.IDiffFilesInterface>, ProjectServiceClient.DiffFilesInterfaceRef.IDiffFilesInterface {
        
        public DiffFilesInterfaceClient() {
        }
        
        public DiffFilesInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiffFilesInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiffFilesInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiffFilesInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int compareFileLetterByLetter(string firstFileName, string secondFileName, int pattern) {
            return base.Channel.compareFileLetterByLetter(firstFileName, secondFileName, pattern);
        }
        
        public System.Threading.Tasks.Task<int> compareFileLetterByLetterAsync(string firstFileName, string secondFileName, int pattern) {
            return base.Channel.compareFileLetterByLetterAsync(firstFileName, secondFileName, pattern);
        }
        
        public double percentCalculate(double distanceLevenhstein, double firstTextLenght) {
            return base.Channel.percentCalculate(distanceLevenhstein, firstTextLenght);
        }
        
        public System.Threading.Tasks.Task<double> percentCalculateAsync(double distanceLevenhstein, double firstTextLenght) {
            return base.Channel.percentCalculateAsync(distanceLevenhstein, firstTextLenght);
        }
    }
}
